### PR TITLE
Issues/uat 71 add uniprot name to annotations

### PR DESCRIPTION
**Pull request by haarts**
Please take a careful look at this. I believe it is correct.

You'll notice some values for uniprotName being hard coded in the test data. This is intentional as these values are inserted during ETL.

I've also updated the [wiki page](https://wiki.thehyve.nl/display/SAN/Database+setup+for+new+datatypes) to reflect the new schema. In addition to this these are the queries I ran on CI to add the columns:

```
alter table deapp.de_protein_annotation add (uniprot_name VARCHAR2(200 CHAR));
comment on column deapp.de_protein_annotation.uniprot_name is 'UniProt name for this analyte.';
```

And for RBM:

```
alter table deapp.de_rbm_annotation add (uniprot_name VARCHAR2(200 CHAR));
comment on column deapp.de_rbm_annotation.uniprot_id is 'UniProtID for this analyte. Refers to the uniprot database (www.uniprot.org), which is loaded as a dictionary in the biomarker table.';
```

### CODE REVIEW

**Comment by JanKanis** [comment]
I think you also need to update RbmModule.rowProperties.

**Comment by JanKanis** [comment]
I think database updates require a corresponding db update script in tranSMARTETL//Kettle-GPL/db-scripts/ and updates to the ddl in transmart-data

**Comment by cataphract** [comment]
@JanKanis Please see if this needs alterations. I would also suggest that you stop dragging your feet and write the tests for your improvements, ESPECIALLY those that involve contracts  (both formal, as in 'expressed in Java interfaces' and informal) with core-api clients. That way we wouldn't have to worry that changes in core-db break downstream.

I can help you with that on Monday, if needed.

**Comment by JanKanis** [comment]
@cataphract This PR in itself is fine, modulo the changes needed in the etl/ddl per my previous comment. I already sent another pull request to transmartApp yesterday with changes in the export code to handle the changes made here (and be robust against similar changes in the future). I totally agree that my core-db changes need tests, but I have not spent a lot of time on that yet in consultation with Robert as getting the other things working had a higher priority.

**Pull request merged**
