### PR TITLE
Create tests for the AllDataProjection and HighDimensionDataTypeResource...

### PR DESCRIPTION
**Pull request by JanKanis**
....dataTypeDescription

This change needs to test a number of features for all existing HD data types. The best way to do that would be parametrized tests, but grails 2.4 does not support that. I have now implemented this with an abstract class that is extended for every data type. 

The rnaseq (not _cog) datatype uses such a different structure in its data query that it needs substantial changes before it passes this test. Since it was created by Wim van der Linden and not used in our current branch I have skipped it for now.

### CODE REVIEW

**Comment by cataphract** [comment]
The tests should codify the contract with the clients. Looking at these tests, they don't expect any specific row or data properties for the several data types.

**Comment by cataphract** [comment]
For instance, would it be correct to get back mrna data that didn't have a gene or intensity data? Probably not, so the tests should reflect this.

**Comment by cataphract** [comment]
Also, please use the 50/72 format for your commits (vim defaults to this for git commit messages).

**Comment by JanKanis** [comment]
@cataphract The test you mention tests if the keys/properties that AllDataProjection.rowProperties/dataProperties say exist, are in fact there. That is the contract these properties have. I thought about asserting which properties a specific data type should have, but that just comes down to writing the list of properties that exist as private data type module members (dataProperties and rowProperties) in two places.

**Comment by cataphract** [comment]
@JanKanis And there's nothing wrong with that. The point is that if for some reason the properties change, the programmer is forced to change the tests. If they were changed accidentally, the error is found; if they were changed on purpose, then at least one thinks twice about the effects it can have downstream.

Also, no better option being available, it's generally preferable to have tests stronger than the contract than weaker than the contract. The first will annoyingly require test changes when the contract is not changed, the second leaves problems unnoticed.

**Comment by cataphract** [comment]
@JanKanis Can you move on this? It's been a week since the last activity.

**Pull request merged**
