### PR TITLE
Add i2b2 tag types.

### PR DESCRIPTION
**Pull request by gijskant**
Add retrieval of tag type values for I2b2 tags.

### CODE REVIEW

**Comment by gijskant** [comment]
@cataphract @forus Can this pull request be merged?

**Comment by cataphract** [comment]
The only comment I'd make is that probably you want `fetch: 'join'` for the `I2b2TagOption` relationship.

**Comment by gijskant** [comment]
@cataphract Fixed.

**Comment by cataphract** [comment]
Ooops, I meant the `I2b2Tag` class, which AFAIU is the only class used at this point.

Anyway, I guess mpore changes will be coming. Just make sure you look out for n+1 queries.

**Comment by gijskant** [comment]
Ah, you're right. Makes sense. Overlooked that one.

**Pull request merged**
